import { ApiProperty } from '@nestjs/swagger';
import { SessionType, SlotStatus } from '@prisma/client';

export class SlotEntity {
  @ApiProperty()
  id: string;

  @ApiProperty()
  professionalId: string;

  @ApiProperty()
  startAt: Date;

  @ApiProperty()
  endAt: Date;

  @ApiProperty({ enum: SlotStatus })
  status: SlotStatus;

  @ApiProperty({ enum: SessionType, nullable: true })
  type: SessionType | null;

  @ApiProperty({
    nullable: true,
    description:
      'Plain external link (Meet/Zoom); never validated or generated by Vitaflow.',
  })
  onlineLink: string | null;
}

export class SlotCounterpartEntity {
  @ApiProperty()
  id: string;

  @ApiProperty()
  name: string;
}

export class UpcomingSlotEntity extends SlotEntity {
  @ApiProperty({
    type: SlotCounterpartEntity,
    description:
      'The other participant — the professional for a user, the booking user for a professional.',
  })
  counterpart: SlotCounterpartEntity;
}
